name = "Blackjack"
uuid = "0ed214cc-019b-47cb-85d9-75dec1bf2518"
authors = ["runner "]
version = "0.1.0"

[deps]
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
PrecompileTools = "1.2.1"
