# Only documentation until GitHub actions docs are set

# Documentation: http://docs.travis-ci.com/user/languages/julia/
# language: julia
# os:
#   - linux
# julia:
#   - 1
# notifications:
#   email: false
# jobs:
#   include:
#     - stage: "Documentation"
#       script:
#         - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
#         - julia --project=docs/ docs/make.jl
#       after_success: skip
