name = "SnoopCompile"
uuid = "aa65fe97-06da-5843-b5b1-d5d13cad87d2"
author = ["Tim Holy <tim.holy@gmail.com>"]
version = "1.7.0"

[deps]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SnoopCompileAnalysis = "9ea4277c-da97-4c3a-afb0-537c066769de"
SnoopCompileBot = "1d5e0e55-7d74-4714-b8d8-efa80e938cf7"
SnoopCompileCore = "e2b509da-e806-4183-be48-004708413034"

[compat]
SnoopCompileAnalysis = "1.7.0"
SnoopCompileBot = "1.7.0"
SnoopCompileCore = "1.7.0"
julia = "1"

[extras]
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
MatLang = "05b439c0-bb3c-11e9-1d8d-1f0a9ebca87a"
MethodAnalysis = "85b6ec6f-f7df-4429-9514-a64bcd9ee824"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ColorTypes", "Documenter", "FixedPointNumbers", "InteractiveUtils", "JLD", "MatLang", "MethodAnalysis", "Pkg", "SparseArrays", "Test"]
