name = "SnoopCompileBot"
uuid = "1d5e0e55-7d74-4714-b8d8-efa80e938cf7"
author = ["Amin Yahyaabadi <aminyahyaabadi74@gmail.com>"]
version = "1.6.1"

[deps]
FilePathsBase = "48062228-2e41-5def-b9a4-89aafe57970f"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
FilePathsBase = "0.9"
YAML = "0.4"
julia = "1"

[extras]
MatLang = "05b439c0-bb3c-11e9-1d8d-1f0a9ebca87a" # only for pathof_noload
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test", "MatLang"]
