name = "SnoopCompileAnalysis"
uuid = "9ea4277c-da97-4c3a-afb0-537c066769de"
author = ["Tim Holy <tim.holy@gmail.com>"]
version = "1.6.0"

[deps]
Cthulhu = "f68482b8-f384-11e8-15f7-abe071a5a75f"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
Cthulhu = "1.2"
OrderedCollections = "1"
julia = "1"
